# =============================================================================
#  DataCorp Secure — configuration PostgreSQL 16 (durcie pour le lab)
# =============================================================================

listen_addresses = '*'
port = 5432
max_connections = 100
hba_file = '/etc/postgresql/pg_hba.conf'

# ----------------------------------------------------------- Authentification
password_encryption = scram-sha-256          # jamais md5

# ----------------------------------------------------------- Chiffrement en transit (TP1)
ssl = on
ssl_cert_file = '/certs/postgres/server.crt'
ssl_key_file  = '/certs/postgres/server.key'
ssl_ca_file   = '/certs/postgres/ca.crt'
ssl_min_protocol_version = 'TLSv1.2'
ssl_prefer_server_ciphers = on

# ----------------------------------------------------------- Journalisation (TP3)
logging_collector = on
log_destination = 'jsonlog'                  # une ligne JSON par événement -> ingestion SIEM
log_directory = '/var/log/postgresql'
log_filename = 'postgresql.log'              # le fichier JSON s'appelle postgresql.json
log_file_mode = 0640
log_rotation_age = 0
log_rotation_size = 0
log_truncate_on_rotation = off

log_connections = off                        # activé au TP3
log_disconnections = off                     # activé au TP3
log_min_error_statement = error              # les requêtes en erreur (ex : permission denied) sont tracées
log_timezone = 'Europe/Paris'
timezone = 'Europe/Paris'

# ----------------------------------------------------------- pgAudit (TP3)
shared_preload_libraries = 'pgaudit'
pgaudit.log = 'none'                         # activé au TP3 via ALTER SYSTEM
pgaudit.log_relation = on
pgaudit.log_parameter = off                  # ne pas écrire les valeurs (données perso) dans les logs
