package main

// Mode expert « pas à pas » : chaque étape est découpée en petites commandes.
// L'étudiant tape la commande n, la console la vérifie, puis la commande n+1
// se débloque. Pour chaque commande, les indices vont du plus vague (l'idée)
// au plus précis (un squelette avec des trous) ; la commande complète (Cmd)
// n'est montrée que si l'étudiant la demande, et coûte des points.
//
// Le lab est partagé : une commande déjà faite par un camarade (« path is
// already in use », « already exists »…) compte comme réussie.

type Task struct {
	Goal   string   `json:"goal"`             // ce qu'il faut obtenir, sans donner la commande
	Hints  []string `json:"hints"`            // du plus vague au plus précis
	Cmd    string   `json:"cmd"`              // solution (révélée à la demande)
	Must   string   `json:"must,omitempty"`   // regex sur la commande tapée (bon outil ?)
	Expect string   `json:"expect,omitempty"` // regex sur la sortie
	OkCode bool     `json:"okCode,omitempty"` // code retour 0 suffit
	Learn  string   `json:"learn,omitempty"`  // ce qu'il faut retenir, affiché après la réussite
}

func T(goal, cmd, expect, learn string, hints ...string) Task {
	return Task{Goal: goal, Cmd: cmd, Expect: expect, Learn: learn, Hints: hints}
}
func (t Task) must(re string) Task { t.Must = re; return t }
func (t Task) code() Task          { t.OkCode = true; return t }

const already = `|already in use|already exists|existe déjà`

var tasks = map[string][]Task{
	// ================================================================ TP1
	"tp1-1": {
		T("Affichez le contenu du vieux script d'ingestion : ~/legacy/ingest_legacy.sh",
			`cat ~/legacy/ingest_legacy.sh`, `DB_PASS`,
			"Le script contient ses mots de passe écrits en dur : toute personne qui peut lire le fichier les obtient.",
			"Commencez par regarder ce qu'il y a dans le dossier du vieux script. :: ls -l ~/legacy/",
			"Pour afficher un fichier texte en entier, la commande tient en 3 lettres : cat. Complétez : :: cat ~/legacy/_______________").must(`\b(cat|less|more|head|tail|sed|nl|bat|grep)\b.*ingest_legacy`),
		T("Ne gardez que les lignes qui contiennent un secret (mots PASS, SECRET ou KEY), avec leur numéro de ligne.",
			`grep -n "PASS\|SECRET\|KEY" ~/legacy/ingest_legacy.sh`, `DB_PASS=`,
			"3 secrets en clair : PostgreSQL (DB_PASS), MinIO et RabbitMQ. Sur un vrai projet, grep est le premier réflexe d'un audit.",
			"grep cherche un mot dans un fichier. Essayez d'abord avec un seul mot : :: grep PASS ~/legacy/ingest_legacy.sh",
			"Ajoutez -n pour voir les numéros de ligne, puis cherchez plusieurs mots avec \\| (« ou ») : :: grep -n \"PASS\\|SECRET\" ~/legacy/ingest_legacy.sh",
			"Il manque encore un mot (les clés d'API) : :: grep -n \"PASS\\|SECRET\\|___\" ~/legacy/ingest_legacy.sh").must(`\bgrep\b`),
		T("Lancez le vieux script : fonctionne-t-il encore ?",
			`bash ~/legacy/ingest_legacy.sh`, `lignes exportées|password authentication failed|not permitted to log in`,
			"Il marche avec VOTRE compte personnel etl_… et dépose un export dans votre dossier. Ce mot de passe sera révoqué dès la fin de l'étape.",
			"Un script shell se lance avec bash, suivi de son chemin : :: bash ~/legacy/_______________").must(`ingest_legacy`),
		T("Affichez les 3 premières lignes du fichier exporté dans votre dossier ~ (son nom commence par export_rh_).",
			`head -3 ~/export_rh_*.csv`, `FR76\d{23}|vault:v\d+:`,
			"Les IBAN sont lisibles en clair dans un fichier que tout le monde peut lire : c'est ce qu'on va corriger.",
			"D'abord, trouvez le nom exact du fichier exporté : :: ls -l ~/export_rh_*",
			"head affiche le début d'un fichier ; -3 limite à 3 lignes : :: head -3 ~/___________*.csv").must(`\b(head|cat|less|sed)\b`),
	},
	"tp1-2": {
		T("Regardez l'état du coffre : est-il initialisé ? est-il fermé (scellé) ?",
			`vault status`, `Sealed`,
			"Initialized = le coffre a déjà reçu ses clés. Sealed true = fermé. Le lab est partagé : un camarade l'a peut-être déjà ouvert.",
			"Toutes les commandes commencent par vault. Tapez-le seul pour voir la liste des sous-commandes : :: vault -h",
			"La sous-commande qui donne l'état tient en un mot anglais (« état ») : :: vault ______"),
		T("Initialisez le coffre et enregistrez le résultat au format JSON dans /lab/work/vault-init.json.",
			`vault operator init -format=json > /lab/work/vault-init.json`, `already initialized`,
			"Vault a créé 5 clés d'ouverture (il en faut 3) et un jeton root. S'il était déjà initialisé, la console a restauré le fichier : rien n'est perdu.",
			"Les opérations d'administrateur sont rangées sous vault operator. Regardez ce qu'il propose : :: vault operator -h",
			"La sous-commande est init. Lisez ses options (cherchez -format) : :: vault operator init -h | head -40",
			"Enregistrer la sortie dans un fichier : commande > fichier. Complétez : :: vault operator init -format=____ > /lab/work/vault-init.json").must(`operator\s+init`).code(),
		T("Affichez les 5 clés d'ouverture et le jeton root.",
			`vault-cles`, `Jeton root`,
			"En entreprise, chaque clé serait donnée à une personne différente : personne ne peut ouvrir le coffre seul.",
			"Le lab fournit une commande qui lit vault-init.json pour vous. Elle commence par vault-… :: ls /lab/scripts/bin/"),
		T("Donnez la 1re clé d'ouverture au coffre.",
			`vault operator unseal "$(jq -r '.unseal_keys_b64[0]' /lab/work/vault-init.json)"`, `Unseal Progress|Sealed\s+false`,
			"Unseal Progress 1/3 : il faut encore 2 clés.",
			"Ouvrir = « unseal », toujours sous vault operator : :: vault operator unseal -h | head -20",
			"Collez la clé 1 affichée par vault-cles à la place de <clé 1> : :: vault operator unseal <clé 1>").must(`operator\s+unseal`),
		T("Donnez une 2e clé, différente de la première.",
			`vault operator unseal "$(jq -r '.unseal_keys_b64[1]' /lab/work/vault-init.json)"`, `Unseal Progress|Sealed\s+false`,
			"Unseal Progress 2/3. Donner deux fois la même clé ne fait pas avancer le compteur.",
			"Même commande, avec la clé 2 de vault-cles : :: vault operator unseal <clé 2>").must(`operator\s+unseal`),
		T("Donnez une 3e clé : le coffre doit s'ouvrir.",
			`vault operator unseal "$(jq -r '.unseal_keys_b64[2]' /lab/work/vault-init.json)"`, `Sealed\s+false`,
			"Sealed false : le coffre est ouvert. C'est le partage de secret de Shamir : 3 clés sur 5.",
			"Même commande, avec la clé 3 : :: vault operator unseal <clé 3>").must(`operator\s+unseal`),
		T("Connectez-vous à Vault en administrateur avec le jeton root.",
			`vault login "$(jq -r .root_token /lab/work/vault-init.json)"`, `Success! You are now authenticated`,
			"Les commandes suivantes utiliseront ce jeton. En vrai, on ne garde jamais le jeton root : on le révoque après la configuration.",
			"Se connecter se dit login. Regardez l'aide : :: vault login -h | head -25",
			"Le jeton root est affiché par vault-cles (il commence par hvs.) : :: vault login <jeton root>").must(`vault\s+login`),
		T("Activez le journal d'audit de Vault, dans le fichier /vault/logs/audit.log.",
			`vault audit enable file file_path=/vault/logs/audit.log`, `Success! Enabled|path is already in use`,
			"Désormais, Vault note chaque demande (qui, quoi, quand). On s'en servira au TP3.",
			"Regardez d'abord quels journaux d'audit existent déjà : :: vault audit list",
			"On en active un avec vault audit enable <type>. Le type qui écrit dans un fichier s'appelle file : :: vault audit enable -h | head -30",
			"Le chemin se donne avec file_path=… Complétez : :: vault audit enable ____ file_path=/vault/logs/audit.log").must(`audit\s+enable`),
		T("Vérifiez que le coffre est bien ouvert.",
			`vault status`, `Sealed\s+false`,
			"Sealed false : étape terminée.",
			"C'est la toute première commande de l'étape : :: vault ______"),
	},
	"tp1-3": {
		T("Activez un moteur de secrets « clé / valeur » (version 2), monté sur le chemin kv/.",
			`vault secrets enable -path=kv kv-v2`, `Success! Enabled`+already,
			"Un moteur de secrets est comme un tiroir du coffre. kv-v2 garde aussi l'historique des versions.",
			"Listez les moteurs de secrets déjà actifs : :: vault secrets list",
			"On en ajoute un avec vault secrets enable. Regardez l'option -path : :: vault secrets enable -h | head -40",
			"Le type clé/valeur version 2 s'appelle kv-v2 ; -path se place AVANT le type : :: vault secrets enable -path=__ kv-v2").must(`secrets\s+enable`),
		T("Rangez le compte PostgreSQL dans kv/datacorp/break-glass/postgres : username=postgres, et le mot de passe qui est dans la variable $POSTGRES_PASSWORD.",
			`vault kv put kv/datacorp/break-glass/postgres username=postgres password="$POSTGRES_PASSWORD"`, `version`,
			"Le mot de passe n'est plus dans un fichier : il est chiffré dans le coffre.",
			"Vérifiez d'abord que la variable contient bien quelque chose (n'affiche que 4 caractères) : :: echo ${POSTGRES_PASSWORD:0:4}…",
			"Écrire un secret : vault kv put <chemin> clé=valeur clé=valeur : :: vault kv put -h | head -30",
			"Complétez : :: vault kv put kv/datacorp/break-glass/postgres username=________ password=$_________________").must(`kv\s+put\s+\S*break-glass/postgres`),
		T("Même chose pour MinIO, dans kv/datacorp/break-glass/minio (variables $MINIO_ROOT_USER et $MINIO_ROOT_PASSWORD).",
			`vault kv put kv/datacorp/break-glass/minio username="$MINIO_ROOT_USER" password="$MINIO_ROOT_PASSWORD"`, `version`, "",
			"Mêmes principes. Les noms des variables MinIO : :: env | grep -o '^MINIO_ROOT_[A-Z]*'",
			"Complétez : :: vault kv put kv/datacorp/break-glass/minio username=$MINIO_ROOT_USER password=$__________________").must(`kv\s+put\s+\S*break-glass/minio`),
		T("Même chose pour RabbitMQ, dans kv/datacorp/break-glass/rabbitmq (variables $RABBITMQ_ADMIN_USER et $RABBITMQ_ADMIN_PASSWORD).",
			`vault kv put kv/datacorp/break-glass/rabbitmq username="$RABBITMQ_ADMIN_USER" password="$RABBITMQ_ADMIN_PASSWORD"`, `version`,
			"Les 3 comptes « bris de glace » sont rangés : on ne s'en sert qu'en cas d'urgence.",
			"Les variables RabbitMQ : :: env | grep -o '^RABBITMQ_ADMIN_[A-Z]*'",
			"Complétez : :: vault kv put kv/datacorp/break-glass/rabbitmq username=$___________________ password=$_______________________").must(`kv\s+put\s+\S*break-glass/rabbitmq`),
		T("Relisez le secret PostgreSQL que vous venez de ranger.",
			`vault kv get kv/datacorp/break-glass/postgres`, `username\s+postgres|"username": "postgres"`,
			"Vault rend le secret, avec sa version et sa date de création.",
			"Voyez d'abord ce qui est rangé dans le tiroir : :: vault kv list kv/datacorp/break-glass",
			"Écrire = put. Lire = … Complétez : :: vault kv ___ kv/datacorp/break-glass/postgres").must(`kv\s+get`),
		T("Demandez à PostgreSQL qui vous êtes, avec la commande sql du lab (elle lit le mot de passe dans Vault).",
			`sql "SELECT current_user"`, `(?m)^\s*postgres\s*$`,
			"La commande sql n'a plus de mot de passe écrit dedans : elle le demande au coffre à chaque fois.",
			"La commande sql du lab prend une requête entre guillemets. Essayez : :: sql \"SELECT version()\"",
			"La fonction SQL qui donne l'utilisateur connecté s'appelle current_user : :: sql \"SELECT ____________\"").must(`\bsql\b`),
	},
	"tp1-4": {
		T("Lisez le script /lab/scripts/setup/tp1-db-dynamique.sh pour comprendre ce qu'il configure dans Vault.",
			`cat /lab/scripts/setup/tp1-db-dynamique.sh`, `vault`,
			"Il active le moteur database et crée le rôle app-ingest : un compte qui ne peut qu'ajouter des transactions, valable 1 h.",
			"Même commande qu'au début du TP pour afficher un fichier : :: ___ /lab/scripts/setup/tp1-db-dynamique.sh").must(`tp1-db-dynamique`),
		T("Lancez ce script.",
			`/lab/scripts/setup/tp1-db-dynamique.sh`, ``,
			"Vault sait maintenant créer des comptes PostgreSQL à la demande.",
			"Le script est exécutable : tapez juste son chemin complet. :: ls -l /lab/scripts/setup/tp1-db-dynamique.sh").must(`tp1-db-dynamique`).code(),
		T("Demandez à Vault un compte PostgreSQL temporaire pour le rôle app-ingest. Notez username, password et lease_id.",
			`vault read database/creds/app-ingest`, `lease_id`,
			"Ce compte n'existait pas il y a une seconde, et il disparaîtra tout seul (lease_duration).",
			"Regardez les rôles que Vault sait créer : :: vault list database/roles",
			"Les identifiants se fabriquent en LISANT database/creds/<rôle> : :: vault read database/creds/_________").must(`vault\s+read\s+\S*creds`),
		T("Avec ce compte, essayez de LIRE les transactions : SELECT count(*) FROM finance.transactions",
			`PGPASSWORD=<password> psql -U <username> -c "SELECT count(*) FROM finance.transactions"`, `permission denied for table transactions`,
			"Refusé : ce compte ne peut qu'ajouter (INSERT). Même volé, il ne permet pas de lire la base. C'est le moindre privilège.",
			"psql est le client PostgreSQL : -U = utilisateur, -c = requête. Regardez l'aide : :: psql --help | head -30",
			"Le mot de passe se place devant, dans PGPASSWORD. Remplacez <password> et <username> par vos valeurs : :: PGPASSWORD=<password> psql -U <username> -c \"SELECT count(*) FROM finance.transactions\"").must(`psql`),
		T("Supprimez ce compte tout de suite, en révoquant son bail (lease).",
			`vault lease revoke <lease_id>`, `revocation|Success`,
			"En cas de fuite, on coupe l'accès en une commande, sans toucher aux autres comptes.",
			"Les baux se gèrent avec vault lease : :: vault lease -h",
			"Supprimer = revoke. Collez le lease_id complet (database/creds/app-ingest/…) : :: vault lease revoke <lease_id>").must(`lease\s+revoke`),
		T("Réessayez de vous connecter avec le même compte (SELECT 1).",
			`PGPASSWORD=<password> psql -U <username> -c "SELECT 1"`, `password authentication failed|does not exist`,
			"Le compte n'existe plus : un mot de passe volé ne sert à rien.",
			"Reprenez la commande psql de tout à l'heure en changeant seulement la requête : :: PGPASSWORD=<password> psql -U <username> -c \"SELECT 1\"").must(`psql`),
	},
	"tp1-5": {
		T("Activez le moteur transit de Vault (le moteur qui chiffre à la demande).",
			`vault secrets enable transit`, `Success! Enabled`+already,
			"transit chiffre et déchiffre, mais ne stocke rien : la clé ne sort jamais de Vault.",
			"Regardez les moteurs déjà actifs : :: vault secrets list",
			"Comme pour kv, sans -path cette fois. Le type s'appelle transit : :: vault secrets enable _______").must(`secrets\s+enable`),
		T("Créez une clé de chiffrement nommée datacorp-pii.",
			`vault write -f transit/keys/datacorp-pii`, `Success|aes256|latest_version`,
			"Une clé AES-256 est créée dans Vault. Personne ne peut la lire, pas même l'administrateur.",
			"Listez les clés qui existent déjà (une erreur = aucune) : :: vault list transit/keys",
			"Créer = écrire sur transit/keys/<nom>. -f = sans donnée : :: vault write -f transit/keys/____________").must(`write.*transit/keys/datacorp-pii`).code(),
		T("Encodez l'IBAN FR7630001007941234567890185 en base64 (Vault attend du base64).",
			`echo -n "FR7630001007941234567890185" | base64`, `RlI3NjMwMDAxMDA3OTQxMjM0NTY3ODkwMTg1`,
			"base64 n'est PAS du chiffrement : c'est juste un encodage, n'importe qui peut le décoder.",
			"Essayez base64 sur un mot simple : :: echo -n bonjour | base64",
			"Faites la même chose avec l'IBAN : :: echo -n \"FR76…\" | ______").must(`base64`),
		T("Chiffrez cet IBAN avec la clé datacorp-pii.",
			`vault write transit/encrypt/datacorp-pii plaintext=$(echo -n "FR7630001007941234567890185" | base64)`, `vault:v\d+:`,
			"ciphertext commence par vault:v1: : la version de la clé qui a chiffré. Relancez : le résultat change à chaque fois (nonce aléatoire).",
			"Chiffrer = écrire sur transit/encrypt/<clé>. Regardez la clé d'abord : :: vault read transit/keys/datacorp-pii",
			"Collez le base64 obtenu après plaintext= : :: vault write transit/encrypt/datacorp-pii plaintext=<base64>",
			"Astuce : $( … ) insère le résultat d'une commande : :: vault write transit/encrypt/datacorp-pii plaintext=$(echo -n \"FR7630001007941234567890185\" | ______)").must(`transit/encrypt`),
		T("Faites tourner la clé : créez-en une nouvelle version.",
			`vault write -f transit/keys/datacorp-pii/rotate`, `Success|latest_version`,
			"Les nouvelles données seront chiffrées en v2 ; les anciennes restent lisibles (Vault garde les anciennes versions).",
			"Notez la version actuelle de la clé : :: vault read -field=latest_version transit/keys/datacorp-pii",
			"Tourner = rotate, au bout du chemin de la clé : :: vault write -f transit/keys/datacorp-pii/______").must(`rotate`).code(),
		T("Chiffrez tous les IBAN déjà en base avec le script /lab/scripts/setup/tp1-chiffrer-existant.sh",
			`/lab/scripts/setup/tp1-chiffrer-existant.sh`, `identifiant révoqué`,
			"Le script a lu chaque IBAN, l'a fait chiffrer par Vault et a réécrit la colonne.",
			"Tapez le chemin complet du script : :: ls -l /lab/scripts/setup/tp1-chiffrer-existant.sh").must(`tp1-chiffrer-existant`),
		T("Vérifiez : affichez le matricule et les 30 premiers caractères de l'IBAN de 3 salariés (table rh.employes).",
			`sql "SELECT matricule, left(iban, 30) FROM rh.employes LIMIT 3"`, `vault:v\d+:`,
			"Les IBAN commencent par vault:v2: : une copie volée de la base ne montre que du charabia.",
			"Regardez les colonnes de la table : :: sql \"\\d rh.employes\"",
			"left(iban, 30) coupe à 30 caractères ; LIMIT 3 garde 3 lignes : :: sql \"SELECT matricule, left(____, 30) FROM rh.employes LIMIT _\"").must(`\bsql\b.*iban`),
	},
	"tp1-6": {
		T("Lancez le script qui branche RabbitMQ et MinIO sur Vault et fait tourner le pipeline : /lab/scripts/setup/tp1-pipeline.sh",
			`/lab/scripts/setup/tp1-pipeline.sh`, ``,
			"Le pipeline tourne avec des identifiants fournis par Vault, jamais écrits dans le code.",
			"Tapez le chemin complet du script : :: ls -l /lab/scripts/setup/tp1-pipeline.sh").must(`tp1-pipeline`).code(),
		T("Qui a écrit les transactions ? Comptez les lignes de finance.transactions pour chaque valeur de la colonne ingere_par.",
			`sql "SELECT ingere_par, count(*) FROM finance.transactions GROUP BY 1"`, `v-approle-`,
			"Les lignes sont écrites par des comptes v-approle-… : des comptes temporaires créés par Vault.",
			"Regardez d'abord quelques lignes : :: sql \"SELECT ingere_par FROM finance.transactions LIMIT 5\"",
			"Pour compter par valeur, on ajoute count(*) et GROUP BY : :: sql \"SELECT ingere_par, count(*) FROM finance.transactions GROUP BY __\"").must(`(?i)group\s+by`),
		T("Votre propre connexion à PostgreSQL est-elle chiffrée ? Interrogez la vue pg_stat_ssl pour VOTRE connexion.",
			`sql "SELECT ssl, version FROM pg_stat_ssl WHERE pid = pg_backend_pid()"`, `TLSv1\.3`,
			"ssl = t et version TLSv1.3 : tout ce qui passe entre la toolbox et la base est chiffré.",
			"La vue pg_stat_ssl liste le chiffrement de chaque connexion : :: sql \"SELECT pid, ssl, version FROM pg_stat_ssl\"",
			"Votre connexion a le numéro pg_backend_pid(). Filtrez : :: sql \"SELECT ssl, version FROM pg_stat_ssl WHERE pid = ________________\"").must(`pg_stat_ssl`),
		T("Essayez de vous connecter SANS chiffrement : cela doit être refusé.",
			`psql -w "host=postgres user=postgres sslmode=disable" -c "SELECT 1" </dev/null`, `no encryption`,
			"PostgreSQL refuse toute connexion non chiffrée (règle hostssl de pg_hba.conf).",
			"psql accepte une chaîne de connexion entre guillemets. Essayez AVEC chiffrement (-w : pas de question de mot de passe) : :: psql -w \"host=postgres user=postgres sslmode=require\" -c \"SELECT 1\" </dev/null",
			"Maintenant sans chiffrement : changez la valeur de sslmode : :: psql -w \"host=postgres user=postgres sslmode=_______\" -c \"SELECT 1\"").must(`sslmode\s*=\s*disable`),
	},
	"tp1-7": {
		T("Fermez le vieux compte legacy_etl : plus de connexion possible, et plus de mot de passe.",
			`sql "ALTER ROLE legacy_etl NOLOGIN PASSWORD NULL"`, `ALTER ROLE`,
			"Le mot de passe DataCorp2019! qui a traîné en clair ne sert plus à rien.",
			"Regardez le compte : :: sql \"SELECT rolname, rolcanlogin FROM pg_roles WHERE rolname = 'legacy_etl'\"",
			"ALTER ROLE <nom> NOLOGIN (plus de connexion) PASSWORD NULL (plus de mot de passe) : :: sql \"ALTER ROLE __________ NOLOGIN PASSWORD ____\"").must(`(?i)alter\s+(role|user)\s+legacy_etl`),
		T("Relancez le vieux script : il doit échouer.",
			`bash /lab/scripts/legacy/ingest_legacy.sh`, `password authentication failed|not permitted to log in`,
			"Un échec, c'est la preuve que la fermeture fonctionne.",
			"Même commande qu'à l'étape 1 : :: bash /lab/scripts/legacy/_______________").must(`ingest_legacy`),
		T("Détruisez l'export en clair laissé dans /tmp (export_rh_….csv).",
			`rm -f /tmp/export_rh_*.csv`, ``,
			"Plus aucune copie en clair des IBAN ne traîne sur le serveur.",
			"Voyez d'abord ce qui traîne : :: ls -l /tmp/export_rh_*",
			"Supprimer = rm ; -f évite l'erreur si le fichier n'existe plus : :: rm -f /tmp/__________*.csv").must(`\brm\b.*export_rh`).code(),
	},
	// ================================================================ TP2
	"tp2-1": {
		T("Affichez toute la table de classification de la DPO : gouvernance.classification_donnees",
			`sql "SELECT * FROM gouvernance.classification_donnees"`, `RESTREINT`,
			"Chaque colonne sensible a un niveau (PUBLIC → RESTREINT) et un traitement à appliquer.",
			"La commande sql du lab. Listez d'abord les tables du schéma gouvernance : :: sql \"\\dt gouvernance.*\"",
			"SELECT * affiche toutes les colonnes : :: sql \"SELECT * FROM gouvernance.______________________\"").must(`classification_donnees`),
		T("Même requête, mais seulement pour le schéma rh, les plus sensibles en premier.",
			`sql "SELECT * FROM gouvernance.classification_donnees WHERE schema_name = 'rh' ORDER BY niveau DESC"`, `RESTREINT`,
			"NIR, IBAN et salaire sont RESTREINT : à chiffrer, masquer ou retirer.",
			"WHERE filtre les lignes. Essayez un filtre : :: sql \"SELECT column_name, niveau FROM gouvernance.classification_donnees WHERE schema_name = 'rh'\"",
			"Ajoutez un tri, les plus sensibles d'abord (DESC) : :: sql \"SELECT * FROM gouvernance.classification_donnees WHERE schema_name = 'rh' ORDER BY ______ DESC\"").must(`(?i)where.*schema_name.*'rh'`),
	},
	"tp2-2": {
		T("Lisez le fichier /lab/scripts/sql/tp2/01-roles.sql : quels droits reçoit chaque rôle ?",
			`cat /lab/scripts/sql/tp2/01-roles.sql`, `GRANT|CREATE ROLE`,
			"Un bloc GRANT par rôle : les droits vont aux rôles, jamais directement aux personnes.",
			"Même commande que pour lire un script : :: ___ /lab/scripts/sql/tp2/01-roles.sql").must(`01-roles`),
		T("Exécutez ce fichier SQL pour créer les rôles.",
			`sql -f /lab/scripts/sql/tp2/01-roles.sql`, `CREATE ROLE|GRANT`+already,
			"Les rôles r_data_engineer, r_data_analyst, r_dpo… existent. (Si un camarade l'a fait, PostgreSQL dit « already exists ».)",
			"La commande sql peut exécuter un fichier entier. Cherchez l'option dans l'aide de psql : :: psql --help | grep -- '-f'",
			"Complétez : :: sql -_ /lab/scripts/sql/tp2/01-roles.sql").must(`\bsql\b.*-f.*01-roles`),
		T("Créez les 6 personnes (alice, bruno, claire…) avec le script /lab/scripts/setup/tp2-comptes.sh",
			`/lab/scripts/setup/tp2-comptes.sh`, ``,
			"Leurs mots de passe sont générés et rangés dans Vault : personne ne les a vus.",
			"Tapez le chemin complet du script : :: ls -l /lab/scripts/setup/tp2-comptes.sh").must(`tp2-comptes`).code(),
		T("Affichez la liste des rôles et de leurs membres.",
			`sql "\du"`, `alice.*r_data_engineer`,
			"alice est membre de r_data_engineer, bruno de r_data_analyst… On lit « qui a quel rôle ».",
			"psql a des raccourcis qui commencent par \\. Essayez \\dn (liste des schémas) : :: sql \"\\dn\"",
			"Le raccourci des rôles : d = describe, u = users : :: sql \"\\__\"").must(`\\du`),
	},
	"tp2-3": {
		T("En tant que bruno (analyste), essayez de lire une ligne de rh.employes.",
			`sql-as bruno "SELECT * FROM rh.employes LIMIT 1"`, `permission denied`,
			"Refusé : l'analyste n'a aucun droit sur les données RH brutes. C'est le résultat attendu.",
			"sql-as <personne> \"REQUÊTE\" : essayez avec quelqu'un qui a le droit : :: sql-as alice \"SELECT count(*) FROM rh.employes\"",
			"Maintenant l'analyste : :: sql-as _____ \"SELECT * FROM rh.employes LIMIT 1\"").must(`sql-as\s+bruno`),
		T("En tant qu'alice, essayez de lire la colonne nir de rh.employes.",
			`sql-as alice "SELECT nir FROM rh.employes LIMIT 1"`, `permission denied`,
			"Refusé : alice a des droits sur certaines colonnes seulement, pas le NIR.",
			"Même principe, colonne nir : :: sql-as alice \"SELECT ___ FROM rh.employes LIMIT 1\"").must(`sql-as\s+alice.*nir`),
		T("En tant qu'alice, lisez les colonnes matricule et departement (2 lignes).",
			`sql-as alice "SELECT matricule, departement FROM rh.employes LIMIT 2"`, `\(2 rows\)`,
			"Accepté : ces colonnes-là lui sont autorisées. On a prouvé que la règle bloque ET qu'elle laisse passer.",
			"Deux colonnes, séparées par une virgule, 2 lignes : :: sql-as alice \"SELECT matricule, __________ FROM rh.employes LIMIT _\"").must(`sql-as\s+alice`),
		T("En tant que david (admin système), essayez de compter les lignes de finance.transactions.",
			`sql-as david "SELECT count(*) FROM finance.transactions"`, `permission denied`,
			"Refusé : administrer les serveurs ne donne pas le droit de lire les données métier.",
			"count(*) compte les lignes : :: sql-as _____ \"SELECT count(*) FROM finance.transactions\"").must(`sql-as\s+david`),
	},
	"tp2-4": {
		T("Lisez la règle de filtrage : /lab/scripts/sql/tp2/02-rls.sql",
			`cat /lab/scripts/sql/tp2/02-rls.sql`, `(?i)policy`,
			"La POLICY dit : chacun ne voit que les lignes de son département.",
			"Comme pour 01-roles.sql : :: ___ /lab/scripts/sql/tp2/02-rls.sql").must(`02-rls`),
		T("Activez cette règle (exécutez le fichier).",
			`sql -f /lab/scripts/sql/tp2/02-rls.sql`, `(?i)(ALTER TABLE|CREATE POLICY)`+already,
			"La Row Level Security est active sur rh.employes.",
			"sql -f <fichier>, comme à l'étape 2 : :: sql -f /lab/scripts/sql/tp2/_________").must(`\bsql\b.*-f.*02-rls`),
		T("En tant que nadia, comptez les salariés par département.",
			`sql-as nadia "SELECT departement, count(*) FROM rh.employes GROUP BY 1"`, `Finance\s*\|\s*32`,
			"Une seule ligne : Finance | 32. Nadia ne voit que son département.",
			"Essayez d'abord une requête simple en tant que nadia : :: sql-as nadia \"SELECT count(*) FROM rh.employes\"",
			"Comptez par département avec GROUP BY : :: sql-as nadia \"SELECT departement, count(*) FROM rh.employes GROUP BY ___________\"").must(`sql-as\s+nadia`),
	},
	"tp2-5": {
		T("Dans /lab/scripts/sql/tp2/03-vues-masquees.sql, repérez les lignes qui contiennent hmac, masquer_email ou tranche_age.",
			`grep -nE "hmac|masquer_email|tranche_age" /lab/scripts/sql/tp2/03-vues-masquees.sql`, `hmac`,
			"hmac = pseudonymiser (clé secrète), masquer_email = cacher, tranche_age = généraliser.",
			"grep -E permet d'écrire le « ou » avec | : :: grep -nE \"hmac\" /lab/scripts/sql/tp2/03-vues-masquees.sql",
			"Ajoutez les deux autres mots : :: grep -nE \"hmac|_____________|___________\" /lab/scripts/sql/tp2/03-vues-masquees.sql").must(`grep.*03-vues`),
		T("Créez la vue masquée en exécutant ce fichier.",
			`sql -f /lab/scripts/sql/tp2/03-vues-masquees.sql`, `(?i)CREATE`+already,
			"La vue analytics.v_employes existe.",
			"sql -f <fichier> : :: sql -f /lab/scripts/sql/tp2/______________________").must(`\bsql\b.*-f.*03-vues`),
		T("En tant que claire (DPO), regardez 3 lignes de analytics.v_employes.",
			`sql-as claire "SELECT * FROM analytics.v_employes LIMIT 3"`, `\(3 rows\)`,
			"Aucun nom, NIR ni IBAN : seulement un pseudonyme, des tranches et des départements.",
			"sql-as claire, puis la requête : :: sql-as claire \"SELECT * FROM analytics.v_employes LIMIT _\"").must(`sql-as\s+claire`),
		T("Combien de personnes restent « uniques » dans la vue ? (une seule personne pour une même combinaison departement, poste, tranche_age, annee_embauche). Nommez le résultat personnes_uniques.",
			`sql-as claire "SELECT count(*) AS personnes_uniques FROM (SELECT 1 FROM analytics.v_employes GROUP BY departement, poste, tranche_age, annee_embauche HAVING count(*) = 1) x"`, `personnes_uniques`,
			"Beaucoup de personnes restent reconnaissables : la vue est pseudonymisée, pas anonyme (question 3).",
			"1) Regroupez par les 4 colonnes et comptez chaque groupe : :: sql-as claire \"SELECT departement, poste, tranche_age, annee_embauche, count(*) FROM analytics.v_employes GROUP BY 1,2,3,4 LIMIT 5\"",
			"2) Ne gardez que les groupes d'une seule personne : HAVING filtre APRÈS le GROUP BY : :: sql-as claire \"SELECT departement, poste FROM analytics.v_employes GROUP BY departement, poste, tranche_age, annee_embauche HAVING count(*) = 1 LIMIT 5\"",
			"3) Comptez ces lignes : mettez la requête entre parenthèses et nommez le résultat : :: sql-as claire \"SELECT count(*) AS personnes_uniques FROM (SELECT 1 FROM analytics.v_employes GROUP BY ___, ___, ___, ___ HAVING count(*) = _) x\"").must(`(?i)having`),
	},
	"tp2-6": {
		T("Créez la fonction de publication : exécutez /lab/scripts/sql/tp2/04-publication.sql",
			`sql -f /lab/scripts/sql/tp2/04-publication.sql`, `(?i)CREATE`+already,
			"publier_vue n'accepte d'ouvrir une vue que si la DPO l'a approuvée.",
			"sql -f <fichier> : :: sql -f /lab/scripts/sql/tp2/_________________").must(`\bsql\b.*-f.*04-publication`),
		T("En tant qu'alice, essayez de publier la vue analytics.v_employes (fonction analytics.publier_vue).",
			`sql-as alice "SELECT analytics.publier_vue('analytics.v_employes')"`, `ERROR|publiée`,
			"Refusé tant que la DPO n'a pas validé. (Si un camarade a déjà fait valider, la publication passe.)",
			"On appelle une fonction SQL avec SELECT nom('argument') : :: sql-as alice \"SELECT analytics.publier_vue('____________________')\"").must(`sql-as\s+alice.*publier_vue`),
		T("En tant que claire, enregistrez l'approbation dans gouvernance.validations_dpo (objet = la vue, decision = APPROUVE, un commentaire).",
			`sql-as claire "INSERT INTO gouvernance.validations_dpo (objet, decision, commentaire) VALUES ('analytics.v_employes', 'APPROUVE', 'OK DPO')"`, `INSERT 0 1`,
			"La décision de la DPO est tracée dans une table : c'est une preuve.",
			"Regardez les colonnes de la table : :: sql \"\\d gouvernance.validations_dpo\"",
			"INSERT INTO table (colonnes) VALUES (valeurs) ; les textes entre apostrophes : :: sql-as claire \"INSERT INTO gouvernance.validations_dpo (objet, decision, commentaire) VALUES ('analytics.v_employes', '________', 'OK DPO')\"").must(`(?i)sql-as\s+claire.*insert`),
		T("En tant qu'alice, publiez à nouveau la vue.",
			`sql-as alice "SELECT analytics.publier_vue('analytics.v_employes')"`, `publiée pour r_data_analyst`,
			"Accepté : Alice prépare, Claire valide. Séparation des tâches.",
			"Exactement la même commande qu'à la sous-étape 2 : :: sql-as alice \"SELECT analytics.publier_vue('analytics.v_employes')\"").must(`publier_vue`),
		T("En tant que bruno, lisez le nombre de salariés par departement et tranche_salaire dans la vue (5 lignes).",
			`sql-as bruno "SELECT departement, tranche_salaire, count(*) FROM analytics.v_employes GROUP BY 1,2 LIMIT 5"`, `tranche_salaire`,
			"Bruno peut enfin analyser, sans jamais savoir qui est qui.",
			"GROUP BY 1,2 = par la 1re et la 2e colonne : :: sql-as bruno \"SELECT departement, tranche_salaire, count(*) FROM analytics.v_employes GROUP BY ___ LIMIT 5\"").must(`sql-as\s+bruno`),
	},
	"tp2-7": {
		T("Lisez la politique MinIO de l'analyste : /lab/minio-policies/data-analyst.json",
			`cat /lab/minio-policies/data-analyst.json`, `curated`,
			"Une seule règle : lire (GetObject, ListBucket) dans curated. Rien sur raw-data.",
			"Un JSON se lit comme un fichier texte : :: ls /lab/minio-policies/").must(`data-analyst`),
		T("Créez alice et bruno dans MinIO avec /lab/scripts/setup/tp2-minio.sh",
			`/lab/scripts/setup/tp2-minio.sh`, ``,
			"Les accès mc « alice/ » et « bruno/ » sont prêts (la console les charge pour vous).",
			"Tapez le chemin complet du script : :: ls -l /lab/scripts/setup/tp2-minio.sh").must(`tp2-minio`).code(),
		T("En tant que bruno, listez le bucket raw-data.",
			`mc ls bruno/raw-data/`, `Access Denied`,
			"Refusé : les données brutes ne sont pas pour l'analyste.",
			"Le client MinIO s'appelle mc. Avec le compte admin, listez les buckets : :: mc ls dc/",
			"Remplacez le compte par bruno et ciblez raw-data : :: mc ls _____/raw-data/").must(`mc\s+ls\s+bruno/raw-data`),
		T("En tant que bruno, essayez d'écrire un fichier (par exemple /etc/hostname) dans curated.",
			`mc cp /etc/hostname bruno/curated/test.txt`, `Access Denied`,
			"Refusé : l'analyste lit, il n'écrit pas.",
			"Copier = mc cp <source> <destination> : :: mc cp /etc/hostname _____/curated/test.txt").must(`mc\s+cp.*bruno/curated`),
		T("En tant qu'alice, listez raw-data/transactions/.",
			`mc ls alice/raw-data/transactions/`, `\d{4}/|\.json|\.csv`,
			"Accepté : la Data Engineer travaille sur les données brutes.",
			"Même commande que pour bruno, avec alice et le dossier transactions : :: mc ls _____/raw-data/transactions/").must(`mc\s+ls\s+alice/`),
	},
	// ================================================================ TP3
	"tp3-1": {
		T("Dans /lab/scripts/sql/tp3/01-audit.sql, repérez les lignes qui parlent de auditeur ou de pgaudit.",
			`grep -nE "auditeur|pgaudit" /lab/scripts/sql/tp3/01-audit.sql`, `(?i)auditeur|pgaudit`,
			"Le rôle auditeur reçoit un droit de lecture sur les tables sensibles : pgAudit trace tout ce que CE rôle pourrait lire.",
			"grep -nE \"mot1|mot2\" fichier : :: grep -nE \"auditeur|_______\" /lab/scripts/sql/tp3/01-audit.sql").must(`01-audit`),
		T("Activez l'audit : exécutez ce fichier.",
			`sql -f /lab/scripts/sql/tp3/01-audit.sql`, `(?i)(CREATE|ALTER|GRANT)`+already,
			"L'audit PostgreSQL est actif sur les tables RESTREINT.",
			"sql -f <fichier> : :: sql -f /lab/scripts/sql/tp3/____________").must(`\bsql\b.*-f.*01-audit`),
		T("En tant que nadia, lisez le nom et le poste de 3 salariés.",
			`sql-as nadia "SELECT nom, poste FROM rh.employes LIMIT 3"`, `\(3 rows\)`,
			"Une lecture tout à fait normale… qui va laisser une trace.",
			"sql-as nadia, 2 colonnes, 3 lignes : :: sql-as nadia \"SELECT nom, _____ FROM rh.employes LIMIT _\"").must(`sql-as\s+nadia`),
		T("Affichez le journal d'audit PostgreSQL.",
			`logs audit`, `AUDIT: OBJECT`,
			"On voit qui (nadia), quoi (SELECT), sur quelle table (rh.employes) et quand.",
			"Tapez logs seul pour voir ses options : :: logs",
			"L'option des lectures de tables sensibles : :: logs _____").must(`\blogs\b`),
	},
	"tp3-2": {
		T("Lisez /lab/scripts/setup/tp3-coffre.sh : que met-il en place ?",
			`cat /lab/scripts/setup/tp3-coffre.sh`, `(?i)retention|lock|worm`,
			"Collecte des journaux MinIO, bucket WORM (Object Lock) et compte de dépôt qui ne peut pas effacer.",
			"cat <chemin> : :: cat /lab/scripts/setup/____________").must(`tp3-coffre`),
		T("Lancez-le. Attention : il a besoin d'un vrai terminal (TTY).",
			`script -qec /lab/scripts/setup/tp3-coffre.sh /dev/null`, ``,
			"Le coffre à preuves est prêt.",
			"script lance un programme dans un faux terminal. Regardez son aide : :: script --help | head -20",
			"script -qec <commande> /dev/null : :: script -qec /lab/scripts/setup/tp3-coffre.sh _________").must(`tp3-coffre`).code(),
		T("Rangez une 1re archive des journaux dans le coffre avec /lab/scripts/seal-logs.sh",
			`/lab/scripts/seal-logs.sh`, ``,
			"L'archive est déposée avec une rétention : personne ne peut la modifier pendant 30 jours.",
			"Tapez le chemin complet : :: ls -l /lab/scripts/seal-logs.sh").must(`seal-logs`).code(),
		T("Essayez d'effacer la preuve (commande effacer-preuve).",
			`effacer-preuve`, `WORM protected`,
			"Refusé : l'objet est protégé en écriture (WORM). Un attaquant ne peut pas effacer ses traces.",
			"C'est une commande du lab : :: ls /lab/scripts/bin/").must(`effacer-preuve`),
	},
	"tp3-3": {
		T("Rejouez la « nuit agitée » avec /lab/scripts/simulate-incidents.sh (sans le lire avant !).",
			`/lab/scripts/simulate-incidents.sh`, `Simulation terminée`,
			"8 événements ont eu lieu. À vous de les retrouver dans les journaux.",
			"Tapez le chemin complet : :: ls -l /lab/scripts/simulate-incidents.sh").must(`simulate-incidents`),
	},
	"tp3-4": {
		T("a) Qui a raté son mot de passe PostgreSQL, et combien de fois ?",
			`logs echecs`, `\d+\s+\w+`,
			"Un compte avec beaucoup d'échecs = tentative de deviner le mot de passe. Notez-le dans votre chronologie.",
			"Tapez logs seul pour voir ses options : :: logs",
			"L'option des mots de passe ratés : :: logs ______").must(`logs\s+echecs`),
		T("b) Qui a lu des tables sensibles (PostgreSQL) ?",
			`logs audit`, `AUDIT: OBJECT`,
			"Attention : ces heures sont à l'heure de Paris.",
			"Autre option de logs : :: logs _____").must(`logs\s+audit`),
		T("c) Quels accès ont été refusés sur le stockage MinIO ?",
			`logs minio`, `Z\s|journal vide`,
			"Ces heures sont en UTC (le Z à la fin). Convertissez avant de trier.",
			"L'option porte le nom du service de stockage : :: logs _____").must(`logs\s+minio`),
		T("d) Quelles demandes Vault a-t-il refusées ?",
			`logs vault`, `Vault`,
			"Rangez maintenant les événements a) à d) dans l'ordre, tout en UTC.",
			"L'option porte le nom du coffre-fort : :: logs _____").must(`logs\s+vault`),
	},
	"tp3-5": {
		T("Lancez le détecteur automatique /lab/scripts/detect.py (c'est un programme Python 3).",
			`python3 /lab/scripts/detect.py`, `CRITIQUE`,
			"Comparez ses alertes à votre chronologie : qu'a-t-il trouvé que vous aviez manqué, et l'inverse ?",
			"Un script Python se lance avec python3. Vérifiez qu'il existe : :: ls -l /lab/scripts/detect.py",
			"Complétez : :: _______ /lab/scripts/detect.py").must(`detect\.py`),
	},
	"tp3-6": {
		T("Rangez une 2e archive, reliée à la 1re : relancez /lab/scripts/seal-logs.sh",
			`/lab/scripts/seal-logs.sh`, ``,
			"L'empreinte de la nouvelle archive inclut celle de la précédente : on ne peut pas en retirer une sans casser la chaîne.",
			"Même script qu'à l'étape 2 : :: ls -l /lab/scripts/seal-logs.sh").must(`seal-logs`).code(),
		T("Dans /lab/work/scelles, vérifiez que chaque archive correspond à son empreinte SHA-256 (fichiers *.sha256).",
			`cd /lab/work/scelles && sha256sum -c *.sha256`, `: OK`,
			"OK partout : les archives n'ont pas été modifiées depuis le scellement.",
			"Voyez ce que contient le dossier : :: ls -l /lab/work/scelles/",
			"sha256sum calcule une empreinte. Essayez sur un fichier : :: sha256sum /etc/hostname",
			"-c (check) vérifie tout un fichier d'empreintes. Placez-vous d'abord dans le dossier : :: cd /lab/work/scelles && sha256sum -_ *.sha256").must(`sha256sum\s+-c`),
		T("Affichez la chaîne des empreintes : /lab/work/scelles/chaine.txt",
			`cat /lab/work/scelles/chaine.txt`, `GENESIS|[0-9a-f]{64}`,
			"Chaque ligne dépend de la précédente : une mini-blockchain de preuves.",
			"cat <chemin> : :: cat /lab/work/scelles/__________").must(`chaine\.txt`),
	},
}

func init() {
	for i := range catalog {
		for j := range catalog[i].Steps {
			s := &catalog[i].Steps[j]
			if t, ok := tasks[s.ID]; ok {
				s.Tasks = t
			}
		}
	}
}
